name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - test-*
      - macos-ci-*
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.job.name }}
    runs-on: ${{ matrix.job.runner }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { runner: macos-12, name: x86_64-apple-darwin }
          - { runner: macos-14, name: aarch64-apple-darwin }
          - { runner: windows-2019, name: x86_64-windows-msvc }
          - { runner: ubuntu-20.04, name: x86_64-linux-gnu }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.job.runner, 'windows')
        with:
          arch: x64

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release -j

      - name: Test Prepare (Windows)
        if: startsWith(matrix.job.runner, 'windows')
        run: |
          New-Item -ItemType Directory -Path "$Env:AppData\gcloud" -Force -ErrorAction SilentlyContinue

      - name: Test (Windows)
        env:
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
          TEST_TABLE_NAME: ${{ secrets.TEST_TABLE_NAME }}
        if: startsWith(matrix.job.runner, 'windows')
        shell: bash
        run: |
          export TEST_CREDENTIALS_PATH="/c/Users/runneradmin/AppData/Roaming/gcloud/application_default_credentials.json"
          echo "TEST_CREDENTIALS_PATH: $TEST_CREDENTIALS_PATH"
          echo -n "$TEST_CREDENTIALS" | base64 --decode > $TEST_CREDENTIALS_PATH
          chmod 600 $TEST_CREDENTIALS_PATH

          ./build/Release/dump_query.exe "${TEST_PROJECT_ID}" "${TEST_TABLE_NAME}"
          ./build/Release/parse_query.exe

      - name: Test (macOS and Linux)
        env:
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
          TEST_TABLE_NAME: ${{ secrets.TEST_TABLE_NAME }}
        if: "!startsWith(matrix.job.runner, 'windows')"
        run: |
          export TEST_CREDENTIALS_PATH="${HOME}/.config/gcloud/application_default_credentials.json"
          mkdir -p "${HOME}/.config/gcloud"
          echo -n "$TEST_CREDENTIALS" | base64 --decode > $TEST_CREDENTIALS_PATH
          chmod 600 $TEST_CREDENTIALS_PATH
          
          ./build/dump_query "${TEST_PROJECT_ID}" "${TEST_TABLE_NAME}"
          ./build/parse_query
